//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cargo()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int cargo_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string description { get; set; }
        public decimal weight_kg { get; set; }
        public Nullable<decimal> volume_m3 { get; set; }
        public string cargo_type { get; set; }
        public string packaging { get; set; }
        public string special_requirements { get; set; }
        public Nullable<decimal> insurance_amount { get; set; }
        public System.DateTime created_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
