//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drivers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public drivers()
        {
            this.routes = new HashSet<routes>();
        }
    
        public int driver_id { get; set; }
        public int user_id { get; set; }
        public string license_number { get; set; }
        public Nullable<System.DateTime> license_expiry { get; set; }
        public Nullable<System.DateTime> medical_check_date { get; set; }
        public Nullable<int> experience_years { get; set; }
        public string phone { get; set; }
        public bool is_available { get; set; }
        public string notes { get; set; }
    
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routes> routes { get; set; }
    }
}
