//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expenses
    {
        public int expense_id { get; set; }
        public int route_id { get; set; }
        public string expense_type { get; set; }
        public decimal amount { get; set; }
        public System.DateTime expense_date { get; set; }
        public string description { get; set; }
        public string receipt_number { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual routes routes { get; set; }
    }
}
