//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gps_tracking
    {
        public int track_id { get; set; }
        public int route_id { get; set; }
        public int car_id { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
        public Nullable<decimal> speed_kmh { get; set; }
        public Nullable<decimal> fuel_level { get; set; }
        public Nullable<decimal> engine_hours { get; set; }
        public System.DateTime tracking_time { get; set; }
        public string address { get; set; }
    
        public virtual routes routes { get; set; }
    }
}
