//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance
    {
        public int maintenance_id { get; set; }
        public int car_id { get; set; }
        public string maintenance_type { get; set; }
        public System.DateTime scheduled_date { get; set; }
        public Nullable<System.DateTime> actual_date { get; set; }
        public string description { get; set; }
        public Nullable<decimal> parts_cost { get; set; }
        public Nullable<decimal> labor_cost { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public string mechanic_name { get; set; }
        public string service_company { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual car car { get; set; }
        public virtual users users { get; set; }
    }
}
