//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qwsEntities1 : DbContext
    {
        public qwsEntities1()
            : base("name=qwsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<drivers> drivers { get; set; }
        public virtual DbSet<expenses> expenses { get; set; }
        public virtual DbSet<gps_tracking> gps_tracking { get; set; }
        public virtual DbSet<maintenance> maintenance { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<routes> routes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
