//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.routes = new HashSet<routes>();
        }
    
        public int order_id { get; set; }
        public string order_number { get; set; }
        public int client_id { get; set; }
        public int cargo_id { get; set; }
        public string status { get; set; }
        public string departure_point { get; set; }
        public string destination_point { get; set; }
        public System.DateTime planned_delivery_date { get; set; }
        public Nullable<System.DateTime> actual_delivery_date { get; set; }
        public Nullable<int> distance_km { get; set; }
        public decimal total_cost { get; set; }
        public Nullable<decimal> paid_amount { get; set; }
        public string payment_status { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routes> routes { get; set; }
    }
}
