//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public routes()
        {
            this.expenses = new HashSet<expenses>();
            this.gps_tracking = new HashSet<gps_tracking>();
        }
    
        public int route_id { get; set; }
        public int order_id { get; set; }
        public int car_id { get; set; }
        public int driver_id { get; set; }
        public string route_number { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> planned_duration_hours { get; set; }
        public Nullable<int> actual_duration_hours { get; set; }
        public Nullable<decimal> fuel_planned { get; set; }
        public Nullable<decimal> fuel_actual { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual drivers drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<expenses> expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gps_tracking> gps_tracking { get; set; }
        public virtual orders orders { get; set; }
    }
}
