//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.drivers = new HashSet<drivers>();
            this.maintenance = new HashSet<maintenance>();
            this.orders = new HashSet<orders>();
            this.orders1 = new HashSet<orders>();
        }
    
        public int ID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string FullName { get; set; }
        public string role { get; set; }
        public string IsBlocked { get; set; }
        public string Заказ { get; set; }
        public string Пункт_отправления { get; set; }
        public string Пункт_выдачи { get; set; }
        public string Дата_доставки { get; set; }
        public Nullable<System.DateTime> Дата_оплаты { get; set; }
        public string Сумма { get; set; }
        public Nullable<int> id_car { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int FailedAttempts { get; set; }
        public Nullable<System.DateTime> BlockedUntil { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string PassportIssuedBy { get; set; }
        public Nullable<System.DateTime> PassportIssueDate { get; set; }
        public Nullable<bool> MustChangePassword { get; set; }
    
        public virtual car car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drivers> drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maintenance> maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders1 { get; set; }
    }
}
